import { BuilderProfile, HomeownerProject } from '../types';

export const INITIAL_BUILDERS: BuilderProfile[] = [
  {
    id: 'b-101',
    fullName: 'Rameshwar Sharma',
    businessName: 'Sharma Civil & Turnkey Infrastructure',
    mobileNumber: '+91 98390 12345',
    whatsappNumber: '+91 98390 12345',
    email: 'ramesh.sharma@sharmabuilders.in',
    city: 'Lucknow',
    areasServed: ['Gomti Nagar', 'Mahanagar', 'Aliganj', 'Indira Nagar', 'Sushant Golf City', 'Vrindavan Yojna'],
    fullAddress: 'Plot 42, Sector 8, Gomti Nagar Extension, Lucknow, UP 226010',
    yearsInConstruction: '15–20 years',
    currentOccupation: 'Turnkey Civil Contractor & Home Builder',
    contractorType: 'Turnkey Contractor',
    storyHowStarted: 'Started 18 years ago as a site supervisor working under Senior PWD Engineers before establishing my own civil construction firm in Lucknow in 2011.',
    housesCompleted: '51–100',
    projectTypes: ['Independent Houses', 'Duplex Houses', 'Villas'],
    maxFloors: 'G+3',
    avgHouseSizeSqFt: 1800,
    residentialPercentage: 90,
    typicalTimeline: '7–9 months',
    timelineAffectingFactors: ['Weather', 'Material availability', 'Client changes'],
    workManaged: ['Foundation', 'RCC', 'Brickwork', 'Plaster', 'Electrical', 'Plumbing', 'Flooring', 'Full turnkey construction'],
    labourModel: 'I have my own permanent labour team',
    availableWorkersCount: 35,
    typicalBudgetRange: '₹25–40 lakh',
    minPricePerSqFt: 1550,
    maxPricePerSqFt: 2200,
    pricingModel: 'Turnkey',
    providesWrittenQuotation: 'Always',
    providesEstimatedTimeline: 'Yes',
    clientChangesHandling: 'We provide itemized estimates for extra scope before executing changes, ensuring 100% price transparency.',
    profilePhoto: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400',
    companyLogo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&q=80&w=200',
    portfolio: [
      {
        id: 'p-1',
        title: 'Modern 2,200 sqft Duplex Villa',
        location: 'Gomti Nagar, Lucknow',
        sqft: 2200,
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
        category: 'Duplex House',
        completionYear: '2024'
      },
      {
        id: 'p-2',
        title: 'G+2 Family Residence',
        location: 'Indira Nagar, Lucknow',
        sqft: 1800,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800',
        category: 'Independent House',
        completionYear: '2023'
      },
      {
        id: 'p-3',
        title: 'RCC Structure & Elevation Work',
        location: 'Vrindavan Yojna, Lucknow',
        sqft: 1500,
        imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=800',
        category: 'Civil Work',
        completionYear: '2024'
      }
    ],
    whatMakesDifferent: 'We deploy anti-seismic RCC frame detailing, use top-brand UltraTech/Ambuja cement and Tata Tiscon TMT steel, and provide weekly video updates to non-resident owners.',
    idealHomeownerType: 'Homeowners who have clear approved house plans and want zero-headache turnkey execution within fixed budgets.',
    alwaysPromised: 'Fixed deadline completion guarantee with zero compromise on steel and cement grade specifications.',
    bestCompletedProject: 'A 3,200 sq.ft luxury triplex home in Gomti Nagar completed in 8.5 months with premium Italian marble flooring and custom teakwood carpentry.',
    verification: {
      phone: true,
      identity: true,
      business: true,
      gst: '09AAAFS4321A1Z8',
      pan: 'AAAFS4321A'
    },
    plan: 'PRIORITY',
    status: 'active',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 28,
    createdAt: '2025-01-10'
  },
  {
    id: 'b-102',
    fullName: 'Gurpreet Singh',
    businessName: 'Apex Royal Builders & Civil Work',
    mobileNumber: '+91 98140 88776',
    whatsappNumber: '+91 98140 88776',
    email: 'gurpreet@apexroyal.in',
    city: 'Jaipur',
    areasServed: ['Vaishali Nagar', 'Mansarovar', 'Jagatpura', 'Malviya Nagar', 'Ajmer Road'],
    fullAddress: 'Shop 14, Apex Tower, Main Ajmer Road, Jaipur, Rajasthan 302006',
    yearsInConstruction: '10–15 years',
    currentOccupation: 'General Contractor & Thekedar',
    contractorType: 'General Contractor',
    storyHowStarted: 'Inherited family brick kilns and transitioned into full-fledged residential house construction across Jaipur region.',
    housesCompleted: '26–50',
    projectTypes: ['Independent Houses', 'Villas', 'Renovation'],
    maxFloors: 'G+2',
    avgHouseSizeSqFt: 1500,
    residentialPercentage: 95,
    typicalTimeline: '5–7 months',
    timelineAffectingFactors: ['Weather', 'Labour availability'],
    workManaged: ['Foundation', 'RCC', 'Brickwork', 'Plaster', 'Flooring', 'Waterproofing'],
    labourModel: 'Mostly my own team',
    availableWorkersCount: 25,
    typicalBudgetRange: '₹15–25 lakh',
    minPricePerSqFt: 1350,
    maxPricePerSqFt: 1850,
    pricingModel: 'Labour + material',
    providesWrittenQuotation: 'Always',
    providesEstimatedTimeline: 'Yes',
    clientChangesHandling: 'Discuss on site directly, note down in physical agreement register and calculate net difference before execution.',
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    companyLogo: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=200',
    portfolio: [
      {
        id: 'p-4',
        title: 'Contemporary Raj-Style Villa',
        location: 'Vaishali Nagar, Jaipur',
        sqft: 2000,
        imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800',
        category: 'Villa',
        completionYear: '2024'
      },
      {
        id: 'p-5',
        title: 'Compact 1,200 sqft G+1 Modern House',
        location: 'Jagatpura, Jaipur',
        sqft: 1200,
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
        category: 'Independent House',
        completionYear: '2023'
      }
    ],
    whatMakesDifferent: 'Expertise in Rajasthan sandstone facades, traditional damp-proofing techniques, and super fast slab casting schedule.',
    idealHomeownerType: 'Budget-conscious families wanting strong structure and elegant elevation without middleman overheads.',
    alwaysPromised: 'Pukka quality materials tested on site and waterproofed foundations.',
    bestCompletedProject: 'A traditional 2,500 sq.ft Jodhpur stone elevation bungalow in Vaishali Nagar with arched verandahs.',
    verification: {
      phone: true,
      identity: true,
      business: true,
      gst: '08BKGPS9988C1Z2',
      pan: 'BKGPS9988C'
    },
    plan: 'PRIORITY',
    status: 'active',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 19,
    createdAt: '2025-01-20'
  },
  {
    id: 'b-103',
    fullName: 'Sanjay Deshmukh',
    businessName: 'Deshmukh Infrastructure & Constructions',
    mobileNumber: '+91 98220 55443',
    whatsappNumber: '+91 98220 55443',
    email: 'contact@deshmukhconstructions.com',
    city: 'Pune',
    areasServed: ['Kothrud', 'Baner', 'Wakad', 'Hadapsar', 'Bavdhan', 'Pimple Saudagar'],
    fullAddress: 'Office 201, Shanti Heights, Paud Road, Kothrud, Pune, MH 411038',
    yearsInConstruction: '20+ years',
    currentOccupation: 'Civil Engineer & Master Contractor',
    contractorType: 'Civil Contractor',
    storyHowStarted: 'Graduated in Civil Engineering from COEP Pune, spent 5 years with L&T Civil division before starting private independent house contracting in 2004.',
    housesCompleted: '100+',
    projectTypes: ['Independent Houses', 'Duplex Houses', 'Commercial Buildings', 'Extensions'],
    maxFloors: 'G+4',
    avgHouseSizeSqFt: 2400,
    residentialPercentage: 85,
    typicalTimeline: '9–12 months',
    timelineAffectingFactors: ['Weather', 'Government approvals', 'Material availability'],
    workManaged: ['Foundation', 'RCC', 'Brickwork', 'Plaster', 'Electrical', 'Plumbing', 'Flooring', 'Waterproofing', 'Full turnkey construction'],
    labourModel: 'I have my own permanent labour team',
    availableWorkersCount: 50,
    typicalBudgetRange: '₹40–60 lakh',
    minPricePerSqFt: 1800,
    maxPricePerSqFt: 2600,
    pricingModel: 'Turnkey',
    providesWrittenQuotation: 'Always',
    providesEstimatedTimeline: 'Yes',
    clientChangesHandling: 'Formal Change Request Order (CRO) issued with cost breakdown prior to execution.',
    profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    companyLogo: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=200',
    portfolio: [
      {
        id: 'p-6',
        title: '3,500 sqft Modern Eco-Residence',
        location: 'Baner, Pune',
        sqft: 3500,
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800',
        category: 'Bungalow',
        completionYear: '2024'
      },
      {
        id: 'p-7',
        title: 'G+3 Multi-Generation Home',
        location: 'Kothrud, Pune',
        sqft: 2800,
        imageUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&q=80&w=800',
        category: 'Duplex House',
        completionYear: '2023'
      }
    ],
    whatMakesDifferent: 'Strict engineering calculations for soil bearing capacity, ultrasonic concrete strength testing on site, and automated stage billing.',
    idealHomeownerType: 'Engineers, IT professionals, and families looking for structural precision, high safety standards, and clear documentation.',
    alwaysPromised: '10-year structural warranty on RCC column beam matrix and foundation.',
    bestCompletedProject: 'A 4,000 sq ft zero-energy solar fitted bungalow in Baner with internal courtyards.',
    verification: {
      phone: true,
      identity: true,
      business: true,
      gst: '27AABCD1234E1Z9',
      pan: 'AABCD1234E'
    },
    plan: 'PRIORITY',
    status: 'active',
    isFeatured: true,
    rating: 4.95,
    reviewCount: 42,
    createdAt: '2024-11-05'
  },
  {
    id: 'b-104',
    fullName: 'Mahesh Reddy',
    businessName: 'Reddy Earth & Structural Thekedars',
    mobileNumber: '+91 99890 33221',
    whatsappNumber: '+91 99890 33221',
    email: 'maheshreddy.build@gmail.com',
    city: 'Hyderabad',
    areasServed: ['Gachibowli', 'Kukatpally', 'Miyapur', 'Manikonda', 'Tellapur', 'Komprelly'],
    fullAddress: 'Plot 108, HMT Swarnapuri Colony, Miyapur, Hyderabad, TS 500049',
    yearsInConstruction: '5–10 years',
    currentOccupation: 'Civil Contractor & Thekedar',
    contractorType: 'Thekedar',
    storyHowStarted: 'Learned brick masonry and concrete casting under my uncle for 6 years before assembling my own dedicated team of mason craftsmen.',
    housesCompleted: '11–25',
    projectTypes: ['Independent Houses', 'Duplex Houses', 'Commercial Buildings'],
    maxFloors: 'G+3',
    avgHouseSizeSqFt: 1600,
    residentialPercentage: 80,
    typicalTimeline: '5–7 months',
    timelineAffectingFactors: ['Weather', 'Material availability'],
    workManaged: ['Foundation', 'RCC', 'Brickwork', 'Plaster', 'Flooring', 'Waterproofing'],
    labourModel: 'Mostly my own team',
    availableWorkersCount: 20,
    typicalBudgetRange: '₹25–40 lakh',
    minPricePerSqFt: 1400,
    maxPricePerSqFt: 1900,
    pricingModel: 'Labour + material',
    providesWrittenQuotation: 'Always',
    providesEstimatedTimeline: 'Yes',
    clientChangesHandling: 'Inform cost variance on site immediately and write in project diary.',
    profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    companyLogo: 'https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&q=80&w=200',
    portfolio: [
      {
        id: 'p-8',
        title: '1,800 sqft G+2 House',
        location: 'Kukatpally, Hyderabad',
        sqft: 1800,
        imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800',
        category: 'Independent House',
        completionYear: '2024'
      }
    ],
    whatMakesDifferent: 'Specialized hard rock excavation experience (very common in Hyderabad terrain) and high density fly-ash brick masonry.',
    idealHomeownerType: 'Homeowners who want honest, hardworking local supervision and transparent material usage.',
    alwaysPromised: 'Personal daily presence at site from 8 AM to 6 PM.',
    bestCompletedProject: 'A 2,100 sq ft house built on rocky terrain in Tellapur within 6.5 months.',
    verification: {
      phone: true,
      identity: true,
      business: false,
      pan: 'ABCMR9012K'
    },
    plan: 'STARTER',
    status: 'active',
    isFeatured: false,
    rating: 4.7,
    reviewCount: 14,
    createdAt: '2025-02-01'
  },
  {
    id: 'b-105',
    fullName: 'Deepak Patel',
    businessName: 'Shraddha Home Builders',
    mobileNumber: '+91 98980 11223',
    whatsappNumber: '+91 98980 11223',
    email: 'info@shraddhabuilders.in',
    city: 'Ahmedabad',
    areasServed: ['Bopal', 'SG Highway', 'Gota', 'Chandkheda', 'Maninagar', 'Prahlad Nagar'],
    fullAddress: '304, Business Plaza, Near Bopal Cross Roads, Ahmedabad, GJ 380058',
    yearsInConstruction: '10–15 years',
    currentOccupation: 'Builder & Turnkey Specialist',
    contractorType: 'Builder',
    storyHowStarted: 'Started doing bungalow extensions in Bopal area in 2012, later expanded into complete plot-to-key residential house construction.',
    housesCompleted: '26–50',
    projectTypes: ['Independent Houses', 'Villas', 'Commercial Buildings'],
    maxFloors: 'G+3',
    avgHouseSizeSqFt: 2000,
    residentialPercentage: 90,
    typicalTimeline: '7–9 months',
    timelineAffectingFactors: ['Weather', 'Client changes'],
    workManaged: ['Foundation', 'RCC', 'Brickwork', 'Plaster', 'Electrical', 'Plumbing', 'Flooring', 'Painting', 'Waterproofing', 'Full turnkey construction'],
    labourModel: 'I have my own permanent labour team',
    availableWorkersCount: 30,
    typicalBudgetRange: '₹40–60 lakh',
    minPricePerSqFt: 1650,
    maxPricePerSqFt: 2300,
    pricingModel: 'Turnkey',
    providesWrittenQuotation: 'Always',
    providesEstimatedTimeline: 'Yes',
    clientChangesHandling: 'Written estimate provided before any variation works.',
    profilePhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400',
    companyLogo: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=200',
    portfolio: [
      {
        id: 'p-9',
        title: '2,500 sqft Modern Guj-Style Home',
        location: 'Bopal, Ahmedabad',
        sqft: 2500,
        imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&q=80&w=800',
        category: 'Villa',
        completionYear: '2024'
      }
    ],
    whatMakesDifferent: 'Includes earthquake resilient foundation design (Zone 3 compliant) and thermal exterior insulation plaster.',
    idealHomeownerType: 'Families looking for reliable quality with modern elevation designs.',
    alwaysPromised: 'Zero leakage guarantee on roof and bathrooms with chemical membrane coating.',
    bestCompletedProject: 'A 3,000 sq ft luxury villa in Bopal with automated gates and modular kitchen included.',
    verification: {
      phone: true,
      identity: true,
      business: true,
      gst: '24ABCPP1234F1Z3'
    },
    plan: 'PRIORITY',
    status: 'active',
    isFeatured: true,
    rating: 4.85,
    reviewCount: 22,
    createdAt: '2025-01-15'
  }
];

export const INITIAL_PROJECTS: HomeownerProject[] = [
  {
    id: 'p-201',
    homeownerName: 'Amitabh Verma',
    mobileNumber: '+91 94150 99887',
    whatsappNumber: '+91 94150 99887',
    city: 'Lucknow',
    locality: 'Gomti Nagar Extension',
    plotSizeSqFt: 1500,
    houseType: 'Independent Houses',
    floors: 'G+1',
    budgetRange: '₹30–40 lakh',
    expectedStartDate: 'Within 30 Days',
    desiredTimeline: '7–9 months',
    constructionPreference: 'Turnkey',
    labourMaterialPreference: 'Complete Material + Labour Turnkey (A-Grade materials)',
    houseMapUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600',
    houseMapName: 'Lucknow_Gomti_G1_Plan_1500sqft.pdf',
    additionalRequirements: 'Need 3 BHK with car parking on ground floor and open terrace garden on 1st floor. Map is fully approved by LDA. Looking for trustworthy local builder who can manage turnkey construction.',
    createdAt: '2026-02-10',
    status: 'open'
  },
  {
    id: 'p-202',
    homeownerName: 'Vikram Singh Rathore',
    mobileNumber: '+91 98290 44556',
    whatsappNumber: '+91 98290 44556',
    city: 'Jaipur',
    locality: 'Mansarovar',
    plotSizeSqFt: 1800,
    houseType: 'Duplex Houses',
    floors: 'G+2',
    budgetRange: '₹40–60 lakh',
    expectedStartDate: 'Next 2 Months',
    desiredTimeline: '9–12 months',
    constructionPreference: 'Labour + material',
    labourMaterialPreference: 'Labour + Material with direct bill transparency',
    houseMapUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=600',
    houseMapName: 'Rathore_Mansarovar_HousePlan.pdf',
    additionalRequirements: 'Corner plot 30x60. Front elevation requires stone cladding. JDA approved house map ready.',
    createdAt: '2026-02-08',
    status: 'open'
  },
  {
    id: 'p-203',
    homeownerName: 'Anil Kulkarni',
    mobileNumber: '+91 97650 12389',
    whatsappNumber: '+91 97650 12389',
    city: 'Pune',
    locality: 'Baner',
    plotSizeSqFt: 2200,
    houseType: 'Villas',
    floors: 'G+2',
    budgetRange: '₹60 lakh–₹1 crore',
    expectedStartDate: 'Immediate',
    desiredTimeline: '9–12 months',
    constructionPreference: 'Turnkey',
    labourMaterialPreference: 'Turnkey with top grade cement and TMT steel',
    houseMapUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=600',
    houseMapName: 'Kulkarni_Baner_VillaPlan.pdf',
    additionalRequirements: '4 BHK luxury villa with double height living room and electric vehicle charging point in parking. PMC architect approved map available.',
    createdAt: '2026-02-05',
    status: 'open'
  }
];
